/**
 * WARNING: Do not change this file. Your changes will be lost.
 * <?php echo date("Y-m-d H:i:s"); ?>
 */

<?php
$helper = Mage::helper('mango');
$d = $helper->getCfgSectionSettings(Mage::registry('cssgen_store'));

if($d['general']['boxed'] == "boxed"){
?>
body.boxed{
<?php
    if(isset($d['general']['out_of_box_color']) && $d['general']['out_of_box_color']){
?>
    background-color:<?php echo $d['general']['out_of_box_color']; ?>;
<?php
    }
    if(isset($d['general']['out_of_box_image']) && $d['general']['out_of_box_image']){
?>
    background-image:url(<?php echo str_replace("http://","//",str_replace("https://","//",Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."mango/page/".$d['general']['out_of_box_image']));?>);
<?php
    } else if(isset($d['general']['out_of_box_color']) && $d['general']['out_of_box_color']) {
?>
    background-image:none;
<?php

    }
?>
}
<?php
}
echo $d['custom_settings']['custom_style'];
if($d['general']['layout'] == "full_width"){
?>
    .catalog-category-view .breadcrumbs > .container, .catalog-product-view .breadcrumbs > .container, .catalog-category-view .main-container > .container, .catalog-product-view .main-container > .container { width: 100%; }

    @media (min-width:1280px){
        .catalog-category-view .breadcrumbs > .container, .catalog-product-view .breadcrumbs > .container, .catalog-category-view .main-container > .container, .catalog-product-view .main-container > .container { padding: 0 20px }
        .catalog-category-view  .col2-left-layout .col-main { width: 80%; }
        .catalog-category-view  .col2-left-layout .col-left { width: 20%; }
        .catalog-category-view  .col2-right-layout .col-main { width: 80%; }
        .catalog-category-view  .col2-right-layout .col-right { width: 20%; }
        .catalog-category-view  .col3-layout .col-wrapper { width: 80%; }
        .catalog-category-view  .col3-layout .col-main { width: 75%; }
        .catalog-category-view  .col3-layout .col-left { width: 25%; }
        .catalog-category-view  .col3-layout .col-right { width: 20%; }
        .catalog-product-view  .col2-left-layout .col-main { width: 80%; }
        .catalog-product-view  .col2-left-layout .col-left { width: 20%; }
        .catalog-product-view  .col2-right-layout .col-main { width: 80%; }
        .catalog-product-view  .col2-right-layout .col-right { width: 20%; }
        .catalog-product-view  .col3-layout .col-wrapper { width: 80%; }
        .catalog-product-view  .col3-layout .col-main { width: 75%; }
        .catalog-product-view  .col3-layout .col-left { width: 25%; }
        .catalog-product-view  .col3-layout .col-right { width: 20%; }
    }
<?php
}
?>
<?php
    $store = Mage::app()->getStore();
    $code  = $store->getCode();
    $popup = Mage::getStoreConfig('mango_settings/newsletter_popup',$code);
?>
<?php
    if($popup["newsletter_custom_style"]){
        echo $popup["newsletter_custom_style"];
    }
?>
#newsletter_popup{
<?php
    if($popup["newsletter_width"]){
        echo "width:".$popup["newsletter_width"].";";
    }
    if($popup["newsletter_height"]){
        echo "height:".$popup["newsletter_height"].";";
    }
    if($popup["newsletter_bg_color"]){
        echo "background-color:".$popup["newsletter_bg_color"].";";
    }
    if(isset($popup["newsletter_bg_image"]) && $popup["newsletter_bg_image"]){
?>
    background-image:url(<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)."mango/newsletter_popup/".$popup['newsletter_bg_image'];?>);
<?php
    }
?>
}